# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Contoso
    Domain: Contoso.svc.cluster.local
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: Contosoord-hlf-ord
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizcd -----------------------------------------
PeerOrgs:
  - Name: Org1
    Domain: Org1.svc.cluster.local
    Template:
      Count: 1
      Hostname: "Org1peer-hlf-peer"