FROM hyperledger/fabric-javaenv:1.3.0
ENV CONTOSO_ARTIFACTS_ACCESS_TOKEN=zzmm4cbhplgchncq3mzp3vhs7vry5oha2qh7zjojs4uy3prtnmaq
RUN source "$HOME/.sdkman/bin/sdkman-init.sh" && sdk install java && sdk install gradle 5.1.1